# SPDX-FileCopyrightText: 2026 Mercury Technologies, Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

# This file might be autogenerated in the future

[
    "aeson"
    "base"
    "bytestring"
    "containers"
    "directory"
    "filepath"
    "hspec"
    "hspec-expectations"
]
